- hosts: smrt_switches
  name: Example
  gather_facts: no
  tasks:
    # NB this assumes that you have taken ownership of the switch as described
    #    in the README.
    - name: Configure the TL-SG108E switch
      connection: local
      rgl.tp_link_easy_smart_switch.smrt_config:
        username: "{{ smrt_username }}"
        password: "{{ smrt_password }}"
        host_ip_address: "{{ smrt_host_ip_address }}"
        host_mac_address: "{{ smrt_host_mac_address }}"
        switch_mac_address: "{{ smrt_switch_mac_address }}"
        # NB undefined ports will be disabled and put in vlan 1 as untagged
        #    ports.
        # NB ports that are not explicitly added in vlans will be disabled
        #    and put in vlan 1 as untagged ports.
        # NB ports without explicit pvid will be deduced from the vlans (use
        #    the first vlan that has the port as an untagged port).
        ports:
          - port: 1
            name: isp
          - port: 2
            name: desktop
          - port: 5
            name: rpi1
          - port: 6
            name: rpi2
          - port: 7
            name: rpi3
          - port: 8
            name: rpi4
        vlans:
          # NB do not remove your management computer (in this example, its in
          #    the desktop port) from vlan 1 because that is the only vlan
          #    that can manage the switch.
          - vlan_id: 1
            name: management
            untagged_ports:
              - desktop
          - vlan_id: 2
            name: wan
            tagged_ports:
              - desktop
            untagged_ports:
              - isp
          - vlan_id: 3
            name: rpi
            tagged_ports:
              - desktop
            untagged_ports:
              - rpi1
              - rpi2
              - rpi3
              - rpi4
